-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ac_alumnos
(
    codalumn integer NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default",
    nacimiento character varying(20) COLLATE pg_catalog."default",
    edad integer,
    matricula character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT ac_alumnos_pkey PRIMARY KEY (codalumn)
);

CREATE TABLE IF NOT EXISTS public.ac_asignaturas
(
    codasig integer NOT NULL,
    nombreasig character varying(40) COLLATE pg_catalog."default",
    precio integer,
    CONSTRAINT ac_asignaturas_pkey PRIMARY KEY (codasig)
);

CREATE TABLE IF NOT EXISTS public.ac_clases
(
    codalumn character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codprofe character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codasig character varying(20) COLLATE pg_catalog."default" NOT NULL,
    aula character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT ac_clases_pkey PRIMARY KEY (codalumn, codprofe, codasig)
);

CREATE TABLE IF NOT EXISTS public.ac_profesores
(
    codprofe integer NOT NULL,
    nombre character varying(40) COLLATE pg_catalog."default",
    direccion character varying(40) COLLATE pg_catalog."default",
    dni character varying(20) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    fecha date,
    puestofijo boolean,
    sueldo integer,
    CONSTRAINT ac_profesores_pkey PRIMARY KEY (codprofe)
);

ALTER TABLE IF EXISTS public.ac_clases
    ADD FOREIGN KEY (codalumn)
    REFERENCES public.ac_alumnos (codalumn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ac_clases
    ADD FOREIGN KEY (codprofe)
    REFERENCES public.ac_profesores (codprofe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ac_clases
    ADD FOREIGN KEY (codasig)
    REFERENCES public.ac_asignaturas (codasig) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;