-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tb2_categoriasoperador
(
    id integer NOT NULL,
    categoria character varying(50) COLLATE pg_catalog."default",
    sueldobase double precision,
    prima double precision,
    CONSTRAINT tb2_categoriasoperador_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb2_clientes
(
    id integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    iddelegacion integer,
    fechaalta date,
    CONSTRAINT tb2_clientes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb2_delegaciones
(
    id integer NOT NULL,
    delegacion character varying(50) COLLATE pg_catalog."default",
    numdias integer,
    CONSTRAINT tb2_delegaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb2_envios
(
    id integer NOT NULL,
    fecharecepcion date,
    fechaentrega date,
    idtipoenvio integer,
    idcliente integer,
    idoperador integer,
    CONSTRAINT tb2_envios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb2_operadores
(
    id integer NOT NULL,
    codigo character varying(20) COLLATE pg_catalog."default",
    nombre character varying(20) COLLATE pg_catalog."default",
    iddelegacion integer,
    idcategoria integer,
    CONSTRAINT tb2_operadores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb2_paises
(
    id integer NOT NULL,
    pais character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT tb2_paises_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb2_tiposenvio
(
    id integer NOT NULL,
    idpaisorigen integer,
    idpaisdestino integer,
    importe double precision,
    descuentopordia double precision,
    CONSTRAINT tb2_tiposenvio_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tb2_clientes
    ADD FOREIGN KEY (iddelegacion)
    REFERENCES public.tb2_delegaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_envios
    ADD FOREIGN KEY (idtipoenvio)
    REFERENCES public.tb2_tiposenvio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_envios
    ADD FOREIGN KEY (idcliente)
    REFERENCES public.tb2_clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_envios
    ADD FOREIGN KEY (idoperador)
    REFERENCES public.tb2_operadores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_operadores
    ADD FOREIGN KEY (iddelegacion)
    REFERENCES public.tb2_delegaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_operadores
    ADD FOREIGN KEY (idcategoria)
    REFERENCES public.tb2_categoriasoperador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_tiposenvio
    ADD FOREIGN KEY (idpaisorigen)
    REFERENCES public.tb2_paises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb2_tiposenvio
    ADD FOREIGN KEY (idpaisdestino)
    REFERENCES public.tb2_paises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;