-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.especialidades
(
    id serial NOT NULL,
    nombre character varying(25),
    cod_jefe_hospital character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.perfiles
(
    id serial NOT NULL,
    nombre character varying(15),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personal
(
    codigo character varying(20) NOT NULL,
    nombre character varying(80),
    idperfil integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.mutuas
(
    id serial NOT NULL,
    nombre character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personal_mutuas
(
    personal_codigo character varying(20) NOT NULL,
    mutuas_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipo_medico
(
    codigo character varying(20) NOT NULL,
    idespecialidad integer,
    cod_medico character varying(20),
    cod_enf1 character varying,
    cod_enf2 character varying,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.celadores
(
    equipo_medico_codigo character varying(20) NOT NULL,
    personal_codigo character varying(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    dni character varying(10) NOT NULL,
    nombre character varying(80),
    idmutua integer,
    PRIMARY KEY (dni)
);

ALTER TABLE IF EXISTS public.especialidades
    ADD FOREIGN KEY (cod_jefe_hospital)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personal
    ADD CONSTRAINT fk1 FOREIGN KEY (idperfil)
    REFERENCES public.perfiles (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.personal_mutuas
    ADD FOREIGN KEY (personal_codigo)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personal_mutuas
    ADD FOREIGN KEY (mutuas_id)
    REFERENCES public.mutuas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipo_medico
    ADD FOREIGN KEY (idespecialidad)
    REFERENCES public.especialidades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.celadores
    ADD FOREIGN KEY (equipo_medico_codigo)
    REFERENCES public.equipo_medico (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.celadores
    ADD FOREIGN KEY (personal_codigo)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD FOREIGN KEY (idmutua)
    REFERENCES public.mutuas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;