-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tbcategorias
(
    id integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tbcategorias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbclientes
(
    nombre character varying(50) COLLATE pg_catalog."default",
    descripcion character varying(50) COLLATE pg_catalog."default",
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tbclientes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbcompaniaenvios
(
    id integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT tbcompaniaenvios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbdetallespedidos
(
    idpedido integer NOT NULL,
    idproducto integer NOT NULL,
    preciounidad double precision,
    cantidad integer,
    descuento double precision,
    CONSTRAINT tbdetallepedidos_pkey PRIMARY KEY (idpedido, idproducto)
);

CREATE TABLE IF NOT EXISTS public.tbempleados
(
    id integer NOT NULL,
    apellidos character varying(50) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default",
    cargo character varying(50) COLLATE pg_catalog."default",
    tratamiento character varying(10) COLLATE pg_catalog."default",
    fechanacimiento date,
    ciudad character varying(50) COLLATE pg_catalog."default",
    pais character varying(50) COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT tbempleados_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbpedidos
(
    id integer NOT NULL,
    idcliente character varying(5) COLLATE pg_catalog."default",
    idempleado integer,
    fechapedido date,
    fechaentrega date,
    fechaenvio date,
    idcompanya integer,
    cargo double precision,
    paisdestinatario character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tbpedidos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbproductos
(
    id integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    idproveedor integer,
    idcategoria integer,
    preciounidad double precision,
    unidadesenpedido integer,
    cantidadporunidad character varying COLLATE pg_catalog."default",
    unidadesenexistencia integer,
    CONSTRAINT tbproductos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbproveedores
(
    id integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    nombrecontacto character varying(50) COLLATE pg_catalog."default",
    cargocontacto character varying(50) COLLATE pg_catalog."default",
    ciudad character varying(50) COLLATE pg_catalog."default",
    region character varying(50) COLLATE pg_catalog."default",
    pais character varying(50) COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT tbproveedores_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tbdetallespedidos
    ADD CONSTRAINT "fk-pedidos" FOREIGN KEY (idpedido)
    REFERENCES public.tbpedidos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbdetallespedidos
    ADD CONSTRAINT "fk-productos" FOREIGN KEY (idproducto)
    REFERENCES public.tbproductos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbpedidos
    ADD CONSTRAINT "fk-compañias" FOREIGN KEY (idcompanya)
    REFERENCES public.tbcompaniaenvios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbpedidos
    ADD CONSTRAINT "fk-clientes" FOREIGN KEY (idcliente)
    REFERENCES public.tbclientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbpedidos
    ADD CONSTRAINT "fk-empleado" FOREIGN KEY (idempleado)
    REFERENCES public.tbempleados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbproductos
    ADD CONSTRAINT "fk-categoria" FOREIGN KEY (idcategoria)
    REFERENCES public.tbcategorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbproductos
    ADD CONSTRAINT "fk-proveedores" FOREIGN KEY (idproveedor)
    REFERENCES public.tbproveedores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;