-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cursos
(
    cod serial NOT NULL,
    titulo character varying(50),
    horas smallint,
    contenido text,
    PRIMARY KEY (cod)
);

CREATE TABLE IF NOT EXISTS public.convocatorias
(
    cod serial NOT NULL,
    cod_curso integer,
    dni_prof character varying(12),
    num_aula smallint,
    fecha_ini date,
    fecha_fin date,
    hora_ini time without time zone,
    hora_fin time without time zone,
    PRIMARY KEY (cod)
);

CREATE TABLE IF NOT EXISTS public.profesores
(
    dni character varying(12) NOT NULL,
    nombre character varying(40),
    telefono character varying(15),
    movil character varying(15),
    email character varying(50),
    PRIMARY KEY (dni)
);

ALTER TABLE IF EXISTS public.convocatorias
    ADD CONSTRAINT "fk-cursos" FOREIGN KEY (cod_curso)
    REFERENCES public.cursos (cod) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.convocatorias
    ADD CONSTRAINT "fk-profesores" FOREIGN KEY (dni_prof)
    REFERENCES public.profesores (dni) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;

END;