-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.mutuas
(
    id serial NOT NULL,
    mutua character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.perfiles
(
    id serial NOT NULL,
    perfil character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    id serial NOT NULL,
    dni character varying(15),
    nombre character varying(30),
    apellidos character varying(60),
    direccion character varying(80),
    telefono character varying(12),
    idmutua integer,
    PRIMARY KEY (id),
    CONSTRAINT ind_dni UNIQUE (dni)
);

CREATE TABLE IF NOT EXISTS public.consultas_urgencias
(
    id serial NOT NULL,
    idpaciente integer,
    fecha date,
    observaciones character varying(250),
    idequipo integer,
    hospitalizacion boolean,
    numero smallint DEFAULT 0,
    familiar character varying(30) DEFAULT NULL,
    telefono character varying(12) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personal
(
    codigo integer NOT NULL,
    idperfil integer,
    nombre character varying(60),
    direccion character varying(100),
    plaza smallint DEFAULT 0,
    cv text,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."mutuas-personal"
(
    idmutua integer NOT NULL,
    codigo integer NOT NULL,
    PRIMARY KEY (idmutua, codigo)
);

CREATE TABLE IF NOT EXISTS public.especialidades
(
    id serial NOT NULL,
    especialidad character varying(25),
    codigo_responsable integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.equipomedico
(
    id serial NOT NULL,
    idespecialidad integer,
    idmedico integer,
    idenfermera1 integer,
    idenfermera2 integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.celadores
(
    id serial NOT NULL,
    idcelador integer,
    idequipomedico integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT "fk-mutuas" FOREIGN KEY (idmutua)
    REFERENCES public.mutuas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.consultas_urgencias
    ADD CONSTRAINT "fk-paciente" FOREIGN KEY (idpaciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personal
    ADD CONSTRAINT "fk-perfiles" FOREIGN KEY (idperfil)
    REFERENCES public.perfiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."mutuas-personal"
    ADD CONSTRAINT "fk-mutuas" FOREIGN KEY (idmutua)
    REFERENCES public.mutuas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."mutuas-personal"
    ADD CONSTRAINT "fk-personal" FOREIGN KEY (codigo)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.especialidades
    ADD CONSTRAINT "fk-personal" FOREIGN KEY (codigo_responsable)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipomedico
    ADD CONSTRAINT "fk-especialidades" FOREIGN KEY (idespecialidad)
    REFERENCES public.especialidades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipomedico
    ADD CONSTRAINT "fk-personal1" FOREIGN KEY (idmedico)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipomedico
    ADD CONSTRAINT "fk-personal2" FOREIGN KEY (idenfermera1)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipomedico
    ADD CONSTRAINT "fk-personal3" FOREIGN KEY (idenfermera2)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.celadores
    ADD CONSTRAINT "fk-equipomedico" FOREIGN KEY (idequipomedico)
    REFERENCES public.equipomedico (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.celadores
    ADD CONSTRAINT "fk-personal" FOREIGN KEY (idcelador)
    REFERENCES public.personal (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;